name: CI/CD
on: push
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Set release version
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
        if: startsWith(github.ref, 'refs/tags/')

      - name: Update build tools
        run: python3 -m pip install -U pip && python3 -m pip install -U wheel build twine

      - name: Build wheel
        run: python3 -m build

      - name: Upload package artifacts
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist/*

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: build
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Download package artifacts
        uses: actions/download-artifact@v2
        with:
          name: dist
          path: /dist

      - name: Install package
        run: pip3 install /dist/*.whl

      - name: Run tests
        run: python3 -m unittest discover -s tests

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: test
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Download wheel
        uses: actions/download-artifact@v2
        with:
          name: dist
      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            *.whl
